name: Continuous Integration
on:
  push:
  pull_request:
  schedule:
    # Run every day at 6:54PM
    - cron: "54 18 * * *"
jobs:
  build:
    name: HHVM ${{matrix.hhvm}} - ${{matrix.os}}
    strategy:
      # Run tests on all OS's and HHVM versions, even if one fails
      fail-fast: false
      matrix:
        os: [ubuntu]
        hhvm:
          - "4.102"
          - "4.128"
          - "4.153"
          - "4.168"
    runs-on: ${{matrix.os}}-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Create branch for version alias
        run: git checkout -b CI_current_pull_request
      - uses: hershel-theodore-layton/actions/hack-lint-test@master
        with:
          hhvm: ${{matrix.hhvm}}
          hhvm_flags: -dhhvm.autoload.enabled=true -dhhvm.autoload.db.path=.var/facts-%{euid}-%{schema}.db
          skip_lint: true
